import js from '@eslint/js'
import { defineConfig, globalIgnores } from 'eslint/config'
import skipFormatting from 'eslint-config-prettier/flat'
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript'
import pluginBoundaries from 'eslint-plugin-boundaries'
import pluginImportX from 'eslint-plugin-import-x'
import pluginOxlint from 'eslint-plugin-oxlint'
import pluginReact from 'eslint-plugin-react'
import pluginReactHooks from 'eslint-plugin-react-hooks'
import tseslint from 'typescript-eslint'

// Feature-Sliced Design layers, highest to lowest. A layer may only import from
// layers strictly below it (enforced by eslint-plugin-boundaries).
const FSD_LAYERS = ['app', 'pages', 'widgets', 'features', 'entities', 'shared'] as const

export default defineConfig(
  {
    name: 'app/files-to-lint',
    files: ['**/*.{ts,mts,tsx}'],
  },

  globalIgnores([
    '**/dist/**',
    '**/dist-ssr/**',
    '**/coverage/**',
    '**/storybook-static/**',
    '**/playwright-report/**',
    '**/test-results/**',
    'src/shared/api/schema.d.ts', // generated by the gen-api-types skill
  ]),

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // ---- React + Hooks ----
  {
    name: 'app/react',
    files: ['**/*.{ts,tsx}'],
    plugins: { react: pluginReact, 'react-hooks': pluginReactHooks },
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    settings: { react: { version: 'detect' } },
    rules: {
      ...pluginReact.configs.flat.recommended.rules,
      ...pluginReactHooks.configs.recommended.rules,
      // React 17+ automatic JSX runtime — no `import React` needed.
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off', // we use TypeScript `interface Props`
    },
  },

  // ---- Import hygiene (eslint-plugin-import-x) ----
  {
    name: 'app/import-x',
    plugins: { 'import-x': pluginImportX },
    settings: {
      'import-x/resolver-next': [createTypeScriptImportResolver({ alwaysTryTypes: true })],
    },
    rules: {
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'type'],
          pathGroups: [{ pattern: '@/**', group: 'internal' }],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import-x/no-duplicates': 'error',
      'import-x/no-self-import': 'error',
      'import-x/no-cycle': ['error', { maxDepth: 3 }],
      'import-x/first': 'error',
      'import-x/newline-after-import': 'error',
    },
  },

  // ---- FSD layer boundaries (eslint-plugin-boundaries) ----
  {
    name: 'app/fsd-boundaries',
    files: ['src/**/*.{ts,mts,tsx}'],
    plugins: { boundaries: pluginBoundaries },
    settings: {
      'boundaries/include': ['src/**/*'],
      'boundaries/elements': FSD_LAYERS.map((type) => ({
        type,
        pattern: `src/${type}/**`,
      })),
      // boundaries resolves import paths (incl. the `@/` alias) via this resolver.
      'import/resolver': { typescript: true },
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          rules: FSD_LAYERS.map((from, i) => ({
            from: { type: from },
            // each layer may import from itself and every lower layer
            allow: { to: { type: FSD_LAYERS.slice(i) } },
          })),
        },
      ],
    },
  },

  // Test & story files: relax rules that don't apply to them.
  {
    name: 'app/test-overrides',
    files: ['**/*.spec.{ts,tsx}', '**/*.stories.{ts,tsx}', 'e2e/**/*.{ts,tsx}'],
    rules: {
      'boundaries/dependencies': 'off',
    },
  },

  ...pluginOxlint.buildFromOxlintConfigFile('.oxlintrc.json'),

  skipFormatting,
)
